services:
  - type: web
    name: gamestore-loja
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PORT
        value: 10000
